### ISSUE TITLE
Invalid certificate

### ISSUE THREAD

**Issue by kav2k** [mozilla-iot/mozilla-iot.github.io#3]
The GitHub Pages site is published on a custom domain, but does not have a valid SSL certificate for that domain.

**Comment by benfrancis** [comment]
Thanks for reporting this issue. SSL is not configured for this static website as it's temporarily hosted on GitHub Pages while we bootstrap the project. Please know that we are aware of this issue and the website will be moving to a new home will full HTTPS support and a shiny green lock! :)

**Comment by benfrancis** [comment]
The website has now been transferred to Mozilla infrastructure with HTTPS fully configured :)
