### ISSUE TITLE
Custom 404 pages

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/mozilla-iot.github.io#8]
If website stays hosted on GitHub Pages, create custom 404 pages

**Comment by vipinkhushu** [comment]
Can i submit a PR for this?

**Comment by benfrancis** [comment]
Probably not, it's no longer hosted on GitHub Pages, it's hosted on some Mozilla infrastructure which pulls the static website from GitHub. I'm not sure how we'd go about defining custom 404s.

**Comment by vipinkhushu** [comment]
Do you know someone whom we can contact regarding this?

**Comment by benfrancis** [comment]
Maybe, but I'm not sure it's really important. This was filed because we were showing the GitHub Pages 404 pages, but the generic one we now show is fine. Closing.
